--Guests with a birthday before 2000:

--Rooms that cost more than 100 gold a night:

--Unique guest names:

--All guests ordered by name (ascending):
--(use ASC or DESC after your ORDER BY [col]

--Top 10 highest price sales:

--All values stored in Lookup tables
--(Lookup tables - just an ID and a name)
--(dynamically combine all theses tables)

--Guest Classes with Levels:
--(generate a new column for level grouping (1-10,10-20,etc.))

--SELECT INSERT statements:
--(INSERT commands auto-generated by SELECT statements; data from one table & stuff it in another)
