DECLARE @TableName VARCHAR(50);
SET @TableName = 'Tavern';

SELECT CONCAT('CREATE TABLE ', @TableName, '(')
UNION ALL
SELECT CONCAT(COLUMN_NAME, ' ', DATA_TYPE,
    (CASE WHEN DATA_TYPE = 'varchar' THEN CONCAT('(', CHARACTER_MAXIMUM_LENGTH, ')') END),
	(CASE WHEN ORDINAL_POSITION IN (
	    SELECT COUNT(ORDINAL_POSITION) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TableName
	) THEN '' ELSE ',' END))
	--',')
	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TableName
UNION ALL
SELECT ');';